---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    company.com/kustomize-component: kube-state-metrics
    company.com/kustomize-component-set: monitoring
  name: company:kube-state-metrics
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: company:kube-state-metrics-resizer
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: monitoring
