---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    company.com/kustomize-component: kube-state-metrics
    company.com/kustomize-component-set: monitoring
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
