---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: company:kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: company:kube-state-metrics-resizer
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
