---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonAnnotations:
  company.com/kustomize-component-set: monitoring

resources:
  - resources/namespace.yml
  - ../../components/kube-state-metrics/

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: doesn-t-matter
    namespace: monitoring
    literals:
      - foo=bar