---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    company.com/kustomize-component: kube-state-metrics
    company.com/kustomize-component-set: monitoring
  name: company:kube-state-metrics-resizer
  namespace: monitoring
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - extensions
    resourceNames:
      - kube-state-metrics
    resources:
      - deployments
    verbs:
      - get
      - update
