---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  company.com/kustomize-component: kube-state-metrics

resources:
  - resources/serviceaccount.yml
  - resources/role.yml
  - resources/rolebinding.yml
  - resources/clusterrole.yml
  - resources/clusterrolebinding.yml
