---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    company.com/kustomize-component: kube-state-metrics
    company.com/kustomize-component-set: monitoring
  name: company:kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: company:kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace:
